// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA6Ajk3m0gnlLaSKcQHKzbWAGW2bflTX0',
    appId: '1:929607589703:web:49cc22e203d4a8772bf662',
    messagingSenderId: '929607589703',
    projectId: 'ecommerce-flutter-972df',
    authDomain: 'ecommerce-flutter-972df.firebaseapp.com',
    storageBucket: 'ecommerce-flutter-972df.firebasestorage.app',
    measurementId: 'G-7JZVBWNS1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNh1FQJIm-KYRqXg-ZHf91Z42zsHSyI_E',
    appId: '1:929607589703:android:414e35e98c34fae82bf662',
    messagingSenderId: '929607589703',
    projectId: 'ecommerce-flutter-972df',
    storageBucket: 'ecommerce-flutter-972df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9q5-TG_mW8j8ngVqtKqVUkYIqTE6osek',
    appId: '1:929607589703:ios:9392fbd1f34630172bf662',
    messagingSenderId: '929607589703',
    projectId: 'ecommerce-flutter-972df',
    storageBucket: 'ecommerce-flutter-972df.firebasestorage.app',
    iosBundleId: 'com.example.viewsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9q5-TG_mW8j8ngVqtKqVUkYIqTE6osek',
    appId: '1:929607589703:ios:9392fbd1f34630172bf662',
    messagingSenderId: '929607589703',
    projectId: 'ecommerce-flutter-972df',
    storageBucket: 'ecommerce-flutter-972df.firebasestorage.app',
    iosBundleId: 'com.example.viewsFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA6Ajk3m0gnlLaSKcQHKzbWAGW2bflTX0',
    appId: '1:929607589703:web:cea403a089ead9d12bf662',
    messagingSenderId: '929607589703',
    projectId: 'ecommerce-flutter-972df',
    authDomain: 'ecommerce-flutter-972df.firebaseapp.com',
    storageBucket: 'ecommerce-flutter-972df.firebasestorage.app',
    measurementId: 'G-VXJFZ1GDVF',
  );
}
